theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: khathiatz
description: test!
show_downloads: false
google_analytics:
